# This is a basic workflow to help you get started with Actions

name: workflow_artifact

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      
      - name: install pycodestyle
        run: pip install pycodestyle

      - name: check pycodestyle
        run: pycodestyle exercise_1 || true


  setup:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: build

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3


      - name: install build
        run: |
          cd exercise_1/
          pip install build
          python3 -m build

      - name: Step 3 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v3
        with: 
          name: assets-for-download
          path: exercise_1/dist/

  download:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: setup

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Step 3 - Use the Upload Artifact GitHub Action
        uses: actions/download-artifact@v3
        with: 
          name: assets-for-download
          path: exercise_1/dist/

      - name: Install file
        run: |
          find exercise_1/dist/ -name "*.whl" | xargs pip install

  fast:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: download

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Step 3 - Use the Upload Artifact GitHub Action
        uses: actions/download-artifact@v3
        with: 
          name: assets-for-download
          path: exercise_1/dist/

      - name: Install file
        run: |
          find exercise_1/dist/ -name "*.whl" | xargs pip install
      
      - name: install pytest
        run: pip install pytest
        
      - name: run test fast
        run: |
          cd exercise_1/
          pytest tests/test_fast.py

  slow1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: fast

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Step 3 - Use the Upload Artifact GitHub Action
        uses: actions/download-artifact@v3
        with: 
          name: assets-for-download
          path: exercise_1/dist/

      - name: Install file
        run: |
          find exercise_1/dist/ -name "*.whl" | xargs pip install

      - name: install pytest
        run: pip install pytest

      - name: test slow
        run: |
          cd exercise_1/
          pytest tests/test_slow_1.py

  slow2:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: fast

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Step 3 - Use the Upload Artifact GitHub Action
        uses: actions/download-artifact@v3
        with: 
          name: assets-for-download
          path: exercise_1/dist/

      - name: Install file
        run: |
          find exercise_1/dist/ -name "*.whl" | xargs pip install

      - name: install pytest
        run: pip install pytest

      - name: test slow
        run: |
          cd exercise_1/
          pytest tests/test_slow_2.py
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [slow1,slow2]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      
      - name: execute
        run: |
          cd exercise_1/
          chmod +x deploy.sh
          ./deploy.sh
